# Generated by Django 2.2.15 on 2020-08-19 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.BooleanField(choices=[(True, 'Boast'), (False, 'Roast')], default=True)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
