# Generated by Django 2.2.15 on 2020-08-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='user_input',
            field=models.CharField(default='', max_length=240),
        ),
    ]
