# Generated by Django 3.1 on 2020-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_boastroast_user_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastroast',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boastroast',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
